/*
 * CDR Banking API
 *
 * Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1.27.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BankingProductsData.Models
{
    /// <summary>
    /// The category to which a product or account belongs. See [here](#product-categories) for more details
    /// </summary>
    /// <value>The category to which a product or account belongs. See [here](#product-categories) for more details</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum BankingProductCategory
    {
        /// <summary>
        /// Enum BUSINESSLOANS for value: BUSINESS_LOANS
        /// </summary>
        [EnumMember(Value = "BUSINESS_LOANS")]
        BUSINESSLOANS = 1,
        /// <summary>
        /// Enum CREDANDCHRGCARDS for value: CRED_AND_CHRG_CARDS
        /// </summary>
        [EnumMember(Value = "CRED_AND_CHRG_CARDS")]
        CREDANDCHRGCARDS = 2,
        /// <summary>
        /// Enum LEASES for value: LEASES
        /// </summary>
        [EnumMember(Value = "LEASES")]
        LEASES = 3,
        /// <summary>
        /// Enum MARGINLOANS for value: MARGIN_LOANS
        /// </summary>
        [EnumMember(Value = "MARGIN_LOANS")]
        MARGINLOANS = 4,
        /// <summary>
        /// Enum OVERDRAFTS for value: OVERDRAFTS
        /// </summary>
        [EnumMember(Value = "OVERDRAFTS")]
        OVERDRAFTS = 5,
        /// <summary>
        /// Enum PERSLOANS for value: PERS_LOANS
        /// </summary>
        [EnumMember(Value = "PERS_LOANS")]
        PERSLOANS = 6,
        /// <summary>
        /// Enum REGULATEDTRUSTACCOUNTS for value: REGULATED_TRUST_ACCOUNTS
        /// </summary>
        [EnumMember(Value = "REGULATED_TRUST_ACCOUNTS")]
        REGULATEDTRUSTACCOUNTS = 7,
        /// <summary>
        /// Enum RESIDENTIALMORTGAGES for value: RESIDENTIAL_MORTGAGES
        /// </summary>
        [EnumMember(Value = "RESIDENTIAL_MORTGAGES")]
        RESIDENTIALMORTGAGES = 8,
        /// <summary>
        /// Enum TERMDEPOSITS for value: TERM_DEPOSITS
        /// </summary>
        [EnumMember(Value = "TERM_DEPOSITS")]
        TERMDEPOSITS = 9,
        /// <summary>
        /// Enum TRADEFINANCE for value: TRADE_FINANCE
        /// </summary>
        [EnumMember(Value = "TRADE_FINANCE")]
        TRADEFINANCE = 10,
        /// <summary>
        /// Enum TRANSANDSAVINGSACCOUNTS for value: TRANS_AND_SAVINGS_ACCOUNTS
        /// </summary>
        [EnumMember(Value = "TRANS_AND_SAVINGS_ACCOUNTS")]
        TRANSANDSAVINGSACCOUNTS = 11,
        /// <summary>
        /// Enum TRAVELCARDS for value: TRAVEL_CARDS
        /// </summary>
        [EnumMember(Value = "TRAVEL_CARDS")]
        TRAVELCARDS = 12    }
}
