/*
 * CDR Banking API
 *
 * Consumer Data Standards APIs created by the Data Standards Body (DSB), with the Data Standards Chair as the decision maker to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1.27.0
 * Contact: contact@consumerdatastandards.gov.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BankingProductsData.Models
{
    /// <summary>
    /// BankingProductEligibility
    /// </summary>
    [DataContract]
        public partial class BankingProductEligibility :  IEquatable<BankingProductEligibility>, IValidatableObject
    {
        /// <summary>
        /// The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning
        /// </summary>
        /// <value>The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum EligibilityTypeEnum
        {
            /// <summary>
            /// Enum BUSINESS for value: BUSINESS
            /// </summary>
            [EnumMember(Value = "BUSINESS")]
            BUSINESS = 1,
            /// <summary>
            /// Enum EMPLOYMENTSTATUS for value: EMPLOYMENT_STATUS
            /// </summary>
            [EnumMember(Value = "EMPLOYMENT_STATUS")]
            EMPLOYMENTSTATUS = 2,
            /// <summary>
            /// Enum MAXAGE for value: MAX_AGE
            /// </summary>
            [EnumMember(Value = "MAX_AGE")]
            MAXAGE = 3,
            /// <summary>
            /// Enum MINAGE for value: MIN_AGE
            /// </summary>
            [EnumMember(Value = "MIN_AGE")]
            MINAGE = 4,
            /// <summary>
            /// Enum MININCOME for value: MIN_INCOME
            /// </summary>
            [EnumMember(Value = "MIN_INCOME")]
            MININCOME = 5,
            /// <summary>
            /// Enum MINTURNOVER for value: MIN_TURNOVER
            /// </summary>
            [EnumMember(Value = "MIN_TURNOVER")]
            MINTURNOVER = 6,
            /// <summary>
            /// Enum NATURALPERSON for value: NATURAL_PERSON
            /// </summary>
            [EnumMember(Value = "NATURAL_PERSON")]
            NATURALPERSON = 7,
            /// <summary>
            /// Enum OTHER for value: OTHER
            /// </summary>
            [EnumMember(Value = "OTHER")]
            OTHER = 8,
            /// <summary>
            /// Enum PENSIONRECIPIENT for value: PENSION_RECIPIENT
            /// </summary>
            [EnumMember(Value = "PENSION_RECIPIENT")]
            PENSIONRECIPIENT = 9,
            /// <summary>
            /// Enum RESIDENCYSTATUS for value: RESIDENCY_STATUS
            /// </summary>
            [EnumMember(Value = "RESIDENCY_STATUS")]
            RESIDENCYSTATUS = 10,
            /// <summary>
            /// Enum STAFF for value: STAFF
            /// </summary>
            [EnumMember(Value = "STAFF")]
            STAFF = 11,
            /// <summary>
            /// Enum STUDENT for value: STUDENT
            /// </summary>
            [EnumMember(Value = "STUDENT")]
            STUDENT = 12        }
        /// <summary>
        /// The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning
        /// </summary>
        /// <value>The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning</value>
        [DataMember(Name="eligibilityType", EmitDefaultValue=false)]
        public EligibilityTypeEnum EligibilityType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BankingProductEligibility" /> class.
        /// </summary>
        /// <param name="eligibilityType">The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning (required).</param>
        /// <param name="additionalValue">Generic field containing additional information relevant to the [eligibilityType](#tocSproducteligibilitytypedoc) specified. Whether mandatory or not is dependent on the value of [eligibilityType](#tocSproducteligibilitytypedoc).</param>
        /// <param name="additionalInfo">Display text providing more information on the [eligibility](#tocSproducteligibilitytypedoc) criteria. Mandatory if the field is set to OTHER.</param>
        /// <param name="additionalInfoUri">Link to a web page with more information on this eligibility criteria.</param>
        public BankingProductEligibility(EligibilityTypeEnum eligibilityType = default(EligibilityTypeEnum), string additionalValue = default(string), string additionalInfo = default(string), string additionalInfoUri = default(string))
        {
            // to ensure "eligibilityType" is required (not null)
            if (eligibilityType == null)
            {
                throw new InvalidDataException("eligibilityType is a required property for BankingProductEligibility and cannot be null");
            }
            else
            {
                this.EligibilityType = eligibilityType;
            }
            this.AdditionalValue = additionalValue;
            this.AdditionalInfo = additionalInfo;
            this.AdditionalInfoUri = additionalInfoUri;
        }
        

        /// <summary>
        /// Generic field containing additional information relevant to the [eligibilityType](#tocSproducteligibilitytypedoc) specified. Whether mandatory or not is dependent on the value of [eligibilityType](#tocSproducteligibilitytypedoc)
        /// </summary>
        /// <value>Generic field containing additional information relevant to the [eligibilityType](#tocSproducteligibilitytypedoc) specified. Whether mandatory or not is dependent on the value of [eligibilityType](#tocSproducteligibilitytypedoc)</value>
        [DataMember(Name="additionalValue", EmitDefaultValue=false)]
        public string AdditionalValue { get; set; }

        /// <summary>
        /// Display text providing more information on the [eligibility](#tocSproducteligibilitytypedoc) criteria. Mandatory if the field is set to OTHER
        /// </summary>
        /// <value>Display text providing more information on the [eligibility](#tocSproducteligibilitytypedoc) criteria. Mandatory if the field is set to OTHER</value>
        [DataMember(Name="additionalInfo", EmitDefaultValue=false)]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Link to a web page with more information on this eligibility criteria
        /// </summary>
        /// <value>Link to a web page with more information on this eligibility criteria</value>
        [DataMember(Name="additionalInfoUri", EmitDefaultValue=false)]
        public string AdditionalInfoUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BankingProductEligibility {\n");
            sb.Append("  EligibilityType: ").Append(EligibilityType).Append("\n");
            sb.Append("  AdditionalValue: ").Append(AdditionalValue).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("  AdditionalInfoUri: ").Append(AdditionalInfoUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BankingProductEligibility);
        }

        /// <summary>
        /// Returns true if BankingProductEligibility instances are equal
        /// </summary>
        /// <param name="input">Instance of BankingProductEligibility to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BankingProductEligibility input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EligibilityType == input.EligibilityType ||
                    (this.EligibilityType != null &&
                    this.EligibilityType.Equals(input.EligibilityType))
                ) && 
                (
                    this.AdditionalValue == input.AdditionalValue ||
                    (this.AdditionalValue != null &&
                    this.AdditionalValue.Equals(input.AdditionalValue))
                ) && 
                (
                    this.AdditionalInfo == input.AdditionalInfo ||
                    (this.AdditionalInfo != null &&
                    this.AdditionalInfo.Equals(input.AdditionalInfo))
                ) && 
                (
                    this.AdditionalInfoUri == input.AdditionalInfoUri ||
                    (this.AdditionalInfoUri != null &&
                    this.AdditionalInfoUri.Equals(input.AdditionalInfoUri))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EligibilityType != null)
                    hashCode = hashCode * 59 + this.EligibilityType.GetHashCode();
                if (this.AdditionalValue != null)
                    hashCode = hashCode * 59 + this.AdditionalValue.GetHashCode();
                if (this.AdditionalInfo != null)
                    hashCode = hashCode * 59 + this.AdditionalInfo.GetHashCode();
                if (this.AdditionalInfoUri != null)
                    hashCode = hashCode * 59 + this.AdditionalInfoUri.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
